function displayAllKaplanMeierRF_HNsupp(pathSUPP)
%displayKaplanMeierRF_HNsupp(pathSUPP,{'Locoregional'},'radiomics_PET')
%displayKaplanMeierRF_HNsupp(pathSUPP,{'Locoregional'},'radiomics_PET',[33,66])
%displayKaplanMeierRF_HNsupp(pathSUPP,{'Distant'},'radiomics_CT')
%displayKaplanMeierRF_HNsupp(pathSUPP,{'Distant'},'radiomics_CT',[33,66])
%displayKaplanMeierRF_HNsupp(pathSUPP,{'Death'},'radiomics_PETCT')
%displayKaplanMeierRF_HNsupp(pathSUPP,{'Death'},'radiomics_PETCT',[33,66])
%displayKaplanMeierRF_HNsupp(pathSUPP,{'Death'},'radiomics_CT')
%displayKaplanMeierRF_HNsupp(pathSUPP,{'Death'},'radiomics_CT',[33,66])
%displayKaplanMeierRF_HNsupp(pathSUPP,{'DeathSign'},'radiomics_CT')
%displayKaplanMeierRF_HNsupp(pathSUPP,{'DeathSign'},'radiomics_CT',[33,66])
%displayKaplanMeierRF_HNsupp(pathSUPP,{'Locoregional'},'clinical')
%displayKaplanMeierRF_HNsupp(pathSUPP,{'Locoregional'},'clinical',[33,66])
%displayKaplanMeierRF_HNsupp(pathSUPP,{'Distant'},'clinical')
%displayKaplanMeierRF_HNsupp(pathSUPP,{'Distant'},'clinical',[33,66])
%displayKaplanMeierRF_HNsupp(pathSUPP,{'Death'},'clinical')
%displayKaplanMeierRF_HNsupp(pathSUPP,{'Death'},'clinical',[33,66])
end